package com.globallogic.procamp.lesson12.entity;



public enum SkillTitle {
  JAVA, OOP, OOD, DESIGN_PATTERNS,
  HIBERNATE, MYBATIS, SQL,
  LIQUIBASE,
  SPRING, EJB, GUICE,
  STRUTS,
  HADOOP, SPARK,
  AKKA, PLAY,
  GWT, REST, JSF,
  ANT, MAVEN, GRADLE,
  MOCKITO, JUNIT,
  ANGULAR, JAVASCRIPT, JQUERY,
  GIT, SVN,
  DOCKER, KUBERNETES,
  CASSANDRA, MONGO, REDIS, DYNAMO_DB,
  JMS, RABBITMQ, ACTIVEMQ,
  SCALA, GROOVY, KOTLIN,
  ELASTIC_SEARCH, LUCENE,
  HTML, CSS,
  JETTY;
}
